#!/usr/bin/env python3
import sys
import os

# Activate virtual environment
venv_path = os.path.join(os.path.dirname(__file__), 'venv', 'bin', 'activate_this.py')
if os.path.exists(venv_path):
    exec(open(venv_path).read(), {'__file__': venv_path})

from app.main import main

if __name__ == "__main__":
    sys.argv[0] = "nova"
    main()
